### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kambleaa007** [postwoman-io/postwoman-cli#2]
i got,
postwoman-cli>postwoman-cli get
'postwoman-cli' is not recognized as an internal or external command,
operable program or batch file.

**Comment by liyasthomas** [comment]
We're just started working on the CLI. Will fix critical bugs in a jiffy and let you know.

**Comment by jamesgeorge007** [comment]
@kambleaa007 kindly follow the instructions as mentioned [here](https://github.com/postwoman-io/postwoman-cli#instructions)

**Comment by kambleaa007** [comment]
@jamesgeorge007 Yes, I tried those, I am using Windows 10, its seems i need to set up environment variables,

![image](https://user-images.githubusercontent.com/19818679/70515190-f20a7680-1b5a-11ea-87bf-5872b78be8eb.png)

![image](https://user-images.githubusercontent.com/19818679/70515169-e61eb480-1b5a-11ea-8277-5b34bee9f7ba.png)

**Comment by jamesgeorge007** [comment]
Yeah, it seems to be an issue with your local environment.
