### ISSUE TITLE
feature: test api with postwoman-collection.json

### ISSUE THREAD

**Issue by yubathom** [postwoman-io/postwoman-cli#3]
**Describe the solution you'd like**
send api requests and report status based on `postwoman-collection.json` file

**Describe alternatives you've considered**
create a new command `send` or `test` to send and report the status of the requests

**Aditional context**
```bash
$ pw-cli send path/to/postwoman-collection.json

regres.in # collection name
┌──────────────────────────────────────────────────┬───────────────┬───────────────┐
│ url                                              │ method        │ status        │
├──────────────────────────────────────────────────┼───────────────┼───────────────┤
│ https://reqres.in/api/users                      │ GET           │ 200           │
├──────────────────────────────────────────────────┼───────────────┼───────────────┤
│ https://reqres.in/api/users/api/users            │ POST          │ 201           │
├──────────────────────────────────────────────────┼───────────────┼───────────────┤
│ https://reqres.in/api/users/api/users/999        │ GET           │ 200           │
├──────────────────────────────────────────────────┼───────────────┼───────────────┤
│ https://reqres.in/api/users/api/users/999        │ DELETE        │ 403           │
└──────────────────────────────────────────────────┴───────────────┴───────────────┘
```
> future: could have some options to display full headers and the response body `--headers --response`

**Comment by liyasthomas** [comment]
![IMG_20200129_104519_050](https://user-images.githubusercontent.com/10395817/73329672-86a07380-4284-11ea-9801-651c7b489736.jpg)
![IMG_20200129_104447_020](https://user-images.githubusercontent.com/10395817/73329673-87390a00-4284-11ea-969c-1f855b4089aa.jpg)
![IMG_20200129_104443_872](https://user-images.githubusercontent.com/10395817/73329675-87390a00-4284-11ea-965d-1be7faa3da8d.jpg)

https://github.com/athul is working on a fully rewritten CLI (WIP) for PW 🔥🎉

**Comment by liyasthomas** [comment]
https://github.com/athul/pwcli is now live. Further improvements regarding CLI will be there! Huge thanks for @athul for making thhis gem!

**Comment by athul** [comment]
![Screen Shot 2020-01-31 at 6 36 15 PM](https://user-images.githubusercontent.com/40897573/73542146-13505a80-445a-11ea-8052-7e9253e74f83.png)
@yubathom done

The post method is a bit buggy with content types but it'll work
